### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by flcdrg** [VerifyTests/Verify.Http#391]
#### Is the feature request related to a problem

Using Verify.Http in a test project that targets netcoreapp3.1 causes the following warning to be displayed:

```text
Warning	NU1701	Package 'Verify.Http 1.0.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	
```

#### Describe the solution

Add netcoreapp3.1 to the list of TargetFrameworks.

This may possibly require some conditional logic on some of the other libraries being included to ensure they are 3.1-compatible

**Comment by SimonCropp** [comment]
this is deployed.

Out of curiosity, what is blocking you from upgrading to net5 or net6?

**Comment by flcdrg** [comment]
As much as I'd love to use .NET 6, Some folks are still using VS2019, and this particular location doesn't want to use non-LTS releases.

**Comment by SimonCropp** [comment]
but net6 is lts

**Comment by flcdrg** [comment]
I know, I know 🙂 . I've even given them a "What's new in .NET 6 and VS 2022" talk! I'd like to think it will happen pretty soon though.

**Comment by SimonCropp** [comment]
send them this https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/ and this https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
